export const DEFAULT_MAINTENANCE_TASKS = [
  { "id": "maint_001", "system": "Enrollables Blackout", "label": "Visita técnica", "defaultPrice": 0 },
  { "id": "maint_002", "system": "Enrollables Blackout", "label": "Diagnóstico técnico", "defaultPrice": 0 },
  { "id": "maint_003", "system": "Enrollables Blackout", "label": "Diagnóstico de garantía", "defaultPrice": 0 },
  { "id": "maint_004", "system": "Enrollables Blackout", "label": "Lavado de tela", "defaultPrice": 0 },
  { "id": "maint_005", "system": "Enrollables Blackout", "label": "Desmanchado de tela", "defaultPrice": 0 },
  { "id": "maint_006", "system": "Enrollables Blackout", "label": "Perfilado de tela", "defaultPrice": 0 },
  { "id": "maint_007", "system": "Enrollables Blackout", "label": "Recentrado de tela", "defaultPrice": 0 },
  { "id": "maint_008", "system": "Enrollables Blackout", "label": "Ajuste de soportes", "defaultPrice": 0 },
  { "id": "maint_009", "system": "Enrollables Blackout", "label": "Ajuste de cenefa", "defaultPrice": 0 },
  { "id": "maint_010", "system": "Enrollables Blackout", "label": "Ajuste de topes", "defaultPrice": 0 },
  { "id": "maint_011", "system": "Enrollables Blackout", "label": "Ajuste de nivelación", "defaultPrice": 0 },
  { "id": "maint_012", "system": "Enrollables Blackout", "label": "Cambio de control", "defaultPrice": 0 },
  { "id": "maint_013", "system": "Enrollables Blackout", "label": "Cambio de cadena", "defaultPrice": 0 },
  { "id": "maint_014", "system": "Enrollables Blackout", "label": "Cambio de tensor", "defaultPrice": 0 },
  { "id": "maint_015", "system": "Enrollables Blackout", "label": "Cambio de soportes", "defaultPrice": 0 },
  { "id": "maint_016", "system": "Enrollables Blackout", "label": "Cambio de tapas laterales", "defaultPrice": 0 },
  { "id": "maint_017", "system": "Enrollables Blackout", "label": "Cambio de terminal inferior", "defaultPrice": 0 },
  { "id": "maint_018", "system": "Enrollables Blackout", "label": "Cambio de tubo", "defaultPrice": 0 },
  { "id": "maint_019", "system": "Enrollables Blackout", "label": "Cambio de cenefa", "defaultPrice": 0 },
  { "id": "maint_020", "system": "Enrollables Blackout", "label": "Cambio de tela", "defaultPrice": 0 },
  { "id": "maint_021", "system": "Enrollables Blackout", "label": "Repegado de tela al tubo", "defaultPrice": 0 },
  { "id": "maint_022", "system": "Enrollables Blackout", "label": "Repegado de tela al terminal inferior", "defaultPrice": 0 },
  { "id": "maint_023", "system": "Enrollables Blackout", "label": "Instalación de tapaluces", "defaultPrice": 0 },
  { "id": "maint_024", "system": "Enrollables Blackout", "label": "Cambio de tapaluces", "defaultPrice": 0 },
  { "id": "maint_025", "system": "Enrollables Blackout", "label": "Instalación de guayas", "defaultPrice": 0 },
  { "id": "maint_026", "system": "Enrollables Blackout", "label": "Cambio de guayas", "defaultPrice": 0 },
  { "id": "maint_027", "system": "Enrollables Blackout", "label": "Motorización", "defaultPrice": 0 },
  { "id": "maint_028", "system": "Enrollables Blackout", "label": "Cambio de motor", "defaultPrice": 0 },
  { "id": "maint_029", "system": "Enrollables Blackout", "label": "Cambio de receptor", "defaultPrice": 0 },
  { "id": "maint_030", "system": "Enrollables Blackout", "label": "Cambio de control remoto", "defaultPrice": 0 },
  { "id": "maint_031", "system": "Enrollables Blackout", "label": "Configuración WiFi", "defaultPrice": 0 },
  { "id": "maint_032", "system": "Enrollables Blackout", "label": "Configuración Alexa", "defaultPrice": 0 },
  { "id": "maint_033", "system": "Enrollables Blackout", "label": "Configuración Google Home", "defaultPrice": 0 },
  { "id": "maint_034", "system": "Enrollables Blackout", "label": "Modernización de mecanismo", "defaultPrice": 0 },
  { "id": "maint_035", "system": "Enrollables Blackout", "label": "Actualización R6 a R8", "defaultPrice": 0 },
  { "id": "maint_036", "system": "Enrollables Blackout", "label": "Actualización R8 a R15", "defaultPrice": 0 },
  { "id": "maint_037", "system": "Enrollables Blackout", "label": "Actualización R15 a R24", "defaultPrice": 0 },
  { "id": "maint_038", "system": "Enrollables Blackout", "label": "Desinstalación", "defaultPrice": 0 },
  { "id": "maint_039", "system": "Enrollables Blackout", "label": "Reinstalación", "defaultPrice": 0 },
  { "id": "maint_040", "system": "Enrollables Blackout", "label": "Traslado de sistema", "defaultPrice": 0 },
  { "id": "maint_041", "system": "Enrollables Blackout", "label": "Servicio preventivo", "defaultPrice": 0 },
  { "id": "maint_042", "system": "Enrollables Blackout", "label": "Servicio correctivo", "defaultPrice": 0 },
  { "id": "maint_043", "system": "Enrollables Blackout", "label": "Cambio completo del sistema", "defaultPrice": 0 },

  { "id": "maint_044", "system": "Enrollables Screen", "label": "Visita técnica", "defaultPrice": 0 },
  { "id": "maint_045", "system": "Enrollables Screen", "label": "Diagnóstico técnico", "defaultPrice": 0 },
  { "id": "maint_046", "system": "Enrollables Screen", "label": "Diagnóstico de garantía", "defaultPrice": 0 },
  { "id": "maint_047", "system": "Enrollables Screen", "label": "Lavado de tela", "defaultPrice": 0 },
  { "id": "maint_048", "system": "Enrollables Screen", "label": "Desmanchado de tela", "defaultPrice": 0 },
  { "id": "maint_049", "system": "Enrollables Screen", "label": "Perfilado de tela", "defaultPrice": 0 },
  { "id": "maint_050", "system": "Enrollables Screen", "label": "Recentrado de tela", "defaultPrice": 0 },
  { "id": "maint_051", "system": "Enrollables Screen", "label": "Ajuste de soportes", "defaultPrice": 0 },
  { "id": "maint_052", "system": "Enrollables Screen", "label": "Ajuste de cenefa", "defaultPrice": 0 },
  { "id": "maint_053", "system": "Enrollables Screen", "label": "Ajuste de topes", "defaultPrice": 0 },
  { "id": "maint_054", "system": "Enrollables Screen", "label": "Ajuste de nivelación", "defaultPrice": 0 },
  { "id": "maint_055", "system": "Enrollables Screen", "label": "Cambio de control", "defaultPrice": 0 },
  { "id": "maint_056", "system": "Enrollables Screen", "label": "Cambio de cadena", "defaultPrice": 0 },
  { "id": "maint_057", "system": "Enrollables Screen", "label": "Cambio de tensor", "defaultPrice": 0 },
  { "id": "maint_058", "system": "Enrollables Screen", "label": "Cambio de soportes", "defaultPrice": 0 },
  { "id": "maint_059", "system": "Enrollables Screen", "label": "Cambio de tapas laterales", "defaultPrice": 0 },
  { "id": "maint_060", "system": "Enrollables Screen", "label": "Cambio de terminal inferior", "defaultPrice": 0 },
  { "id": "maint_061", "system": "Enrollables Screen", "label": "Cambio de tubo", "defaultPrice": 0 },
  { "id": "maint_062", "system": "Enrollables Screen", "label": "Cambio de cenefa", "defaultPrice": 0 },
  { "id": "maint_063", "system": "Enrollables Screen", "label": "Cambio de tela", "defaultPrice": 0 },
  { "id": "maint_064", "system": "Enrollables Screen", "label": "Repegado de tela al tubo", "defaultPrice": 0 },
  { "id": "maint_065", "system": "Enrollables Screen", "label": "Repegado de tela al terminal inferior", "defaultPrice": 0 },
  { "id": "maint_066", "system": "Enrollables Screen", "label": "Instalación de guayas", "defaultPrice": 0 },
  { "id": "maint_067", "system": "Enrollables Screen", "label": "Cambio de guayas", "defaultPrice": 0 },
  { "id": "maint_068", "system": "Enrollables Screen", "label": "Motorización", "defaultPrice": 0 },
  { "id": "maint_069", "system": "Enrollables Screen", "label": "Cambio de motor", "defaultPrice": 0 },
  { "id": "maint_070", "system": "Enrollables Screen", "label": "Cambio de receptor", "defaultPrice": 0 },
  { "id": "maint_071", "system": "Enrollables Screen", "label": "Cambio de control remoto", "defaultPrice": 0 },
  { "id": "maint_072", "system": "Enrollables Screen", "label": "Configuración WiFi", "defaultPrice": 0 },
  { "id": "maint_073", "system": "Enrollables Screen", "label": "Configuración Alexa", "defaultPrice": 0 },
  { "id": "maint_074", "system": "Enrollables Screen", "label": "Configuración Google Home", "defaultPrice": 0 },
  { "id": "maint_075", "system": "Enrollables Screen", "label": "Modernización de mecanismo", "defaultPrice": 0 },
  { "id": "maint_076", "system": "Enrollables Screen", "label": "Actualización R6 a R8", "defaultPrice": 0 },
  { "id": "maint_077", "system": "Enrollables Screen", "label": "Actualización R8 a R15", "defaultPrice": 0 },
  { "id": "maint_078", "system": "Enrollables Screen", "label": "Actualización R15 a R24", "defaultPrice": 0 },
  { "id": "maint_079", "system": "Enrollables Screen", "label": "Desinstalación", "defaultPrice": 0 },
  { "id": "maint_080", "system": "Enrollables Screen", "label": "Reinstalación", "defaultPrice": 0 },
  { "id": "maint_081", "system": "Enrollables Screen", "label": "Traslado de sistema", "defaultPrice": 0 },
  { "id": "maint_082", "system": "Enrollables Screen", "label": "Servicio preventivo", "defaultPrice": 0 },
  { "id": "maint_083", "system": "Enrollables Screen", "label": "Servicio correctivo", "defaultPrice": 0 },
  { "id": "maint_084", "system": "Enrollables Screen", "label": "Cambio completo del sistema", "defaultPrice": 0 },

  { "id": "maint_085", "system": "Sheer Elegance", "label": "Visita técnica", "defaultPrice": 0 },
  { "id": "maint_086", "system": "Sheer Elegance", "label": "Diagnóstico técnico", "defaultPrice": 0 },
  { "id": "maint_087", "system": "Sheer Elegance", "label": "Diagnóstico de garantía", "defaultPrice": 0 },
  { "id": "maint_088", "system": "Sheer Elegance", "label": "Lavado de tela", "defaultPrice": 0 },
  { "id": "maint_089", "system": "Sheer Elegance", "label": "Perfilado de tela", "defaultPrice": 0 },
  { "id": "maint_090", "system": "Sheer Elegance", "label": "Recentrado de tela", "defaultPrice": 0 },
  { "id": "maint_091", "system": "Sheer Elegance", "label": "Sincronización de franjas", "defaultPrice": 0 },
  { "id": "maint_092", "system": "Sheer Elegance", "label": "Corrección de bandas", "defaultPrice": 0 },
  { "id": "maint_093", "system": "Sheer Elegance", "label": "Corrección de enrollado irregular", "defaultPrice": 0 },
  { "id": "maint_094", "system": "Sheer Elegance", "label": "Ajuste de soportes", "defaultPrice": 0 },
  { "id": "maint_095", "system": "Sheer Elegance", "label": "Ajuste de cenefa", "defaultPrice": 0 },
  { "id": "maint_096", "system": "Sheer Elegance", "label": "Ajuste de topes", "defaultPrice": 0 },
  { "id": "maint_097", "system": "Sheer Elegance", "label": "Cambio de control", "defaultPrice": 0 },
  { "id": "maint_098", "system": "Sheer Elegance", "label": "Cambio de cadena", "defaultPrice": 0 },
  { "id": "maint_099", "system": "Sheer Elegance", "label": "Cambio de tensor", "defaultPrice": 0 },
  { "id": "maint_100", "system": "Sheer Elegance", "label": "Cambio de soportes", "defaultPrice": 0 },
  { "id": "maint_101", "system": "Sheer Elegance", "label": "Cambio de terminal", "defaultPrice": 0 },
  { "id": "maint_102", "system": "Sheer Elegance", "label": "Cambio de tubo", "defaultPrice": 0 },
  { "id": "maint_103", "system": "Sheer Elegance", "label": "Cambio de tela", "defaultPrice": 0 },
  { "id": "maint_104", "system": "Sheer Elegance", "label": "Motorización", "defaultPrice": 0 },
  { "id": "maint_105", "system": "Sheer Elegance", "label": "Cambio de motor", "defaultPrice": 0 },
  { "id": "maint_106", "system": "Sheer Elegance", "label": "Cambio de receptor", "defaultPrice": 0 },
  { "id": "maint_107", "system": "Sheer Elegance", "label": "Cambio de control remoto", "defaultPrice": 0 },
  { "id": "maint_108", "system": "Sheer Elegance", "label": "Configuración WiFi", "defaultPrice": 0 },
  { "id": "maint_109", "system": "Sheer Elegance", "label": "Configuración Alexa", "defaultPrice": 0 },
  { "id": "maint_110", "system": "Sheer Elegance", "label": "Configuración Google Home", "defaultPrice": 0 },
  { "id": "maint_111", "system": "Sheer Elegance", "label": "Modernización de mecanismo", "defaultPrice": 0 },
  { "id": "maint_112", "system": "Sheer Elegance", "label": "Actualización R6 a R8", "defaultPrice": 0 },
  { "id": "maint_113", "system": "Sheer Elegance", "label": "Actualización R8 a R15", "defaultPrice": 0 },
  { "id": "maint_114", "system": "Sheer Elegance", "label": "Actualización R15 a R24", "defaultPrice": 0 },
  { "id": "maint_115", "system": "Sheer Elegance", "label": "Desinstalación", "defaultPrice": 0 },
  { "id": "maint_116", "system": "Sheer Elegance", "label": "Reinstalación", "defaultPrice": 0 },
  { "id": "maint_117", "system": "Sheer Elegance", "label": "Traslado de sistema", "defaultPrice": 0 },
  { "id": "maint_118", "system": "Sheer Elegance", "label": "Servicio preventivo", "defaultPrice": 0 },
  { "id": "maint_119", "system": "Sheer Elegance", "label": "Servicio correctivo", "defaultPrice": 0 },
  { "id": "maint_120", "system": "Sheer Elegance", "label": "Cambio completo del sistema", "defaultPrice": 0 },

  { "id": "maint_121", "system": "Panel Japones", "label": "Visita técnica", "defaultPrice": 0 },
  { "id": "maint_122", "system": "Panel Japones", "label": "Diagnóstico técnico", "defaultPrice": 0 },
  { "id": "maint_123", "system": "Panel Japones", "label": "Diagnóstico de garantía", "defaultPrice": 0 },
  { "id": "maint_124", "system": "Panel Japones", "label": "Lavado de paneles", "defaultPrice": 0 },
  { "id": "maint_125", "system": "Panel Japones", "label": "Limpieza de riel", "defaultPrice": 0 },
  { "id": "maint_126", "system": "Panel Japones", "label": "Ajuste de paneles", "defaultPrice": 0 },
  { "id": "maint_127", "system": "Panel Japones", "label": "Ajuste de traslape", "defaultPrice": 0 },
  { "id": "maint_128", "system": "Panel Japones", "label": "Ajuste de recorrido", "defaultPrice": 0 },
  { "id": "maint_129", "system": "Panel Japones", "label": "Cambio de panel", "defaultPrice": 0 },
  { "id": "maint_130", "system": "Panel Japones", "label": "Cambio de velcro", "defaultPrice": 0 },
  { "id": "maint_131", "system": "Panel Japones", "label": "Cambio de carros", "defaultPrice": 0 },
  { "id": "maint_132", "system": "Panel Japones", "label": "Cambio de cordones", "defaultPrice": 0 },
  { "id": "maint_133", "system": "Panel Japones", "label": "Cambio de tensores", "defaultPrice": 0 },
  { "id": "maint_134", "system": "Panel Japones", "label": "Cambio de topes", "defaultPrice": 0 },
  { "id": "maint_135", "system": "Panel Japones", "label": "Cambio de riel", "defaultPrice": 0 },
  { "id": "maint_136", "system": "Panel Japones", "label": "Cambio de correa dentada", "defaultPrice": 0 },
  { "id": "maint_137", "system": "Panel Japones", "label": "Motorización", "defaultPrice": 0 },
  { "id": "maint_138", "system": "Panel Japones", "label": "Cambio de motor", "defaultPrice": 0 },
  { "id": "maint_139", "system": "Panel Japones", "label": "Cambio de receptor", "defaultPrice": 0 },
  { "id": "maint_140", "system": "Panel Japones", "label": "Cambio de control remoto", "defaultPrice": 0 },
  { "id": "maint_141", "system": "Panel Japones", "label": "Configuración WiFi", "defaultPrice": 0 },
  { "id": "maint_142", "system": "Panel Japones", "label": "Configuración Alexa", "defaultPrice": 0 },
  { "id": "maint_143", "system": "Panel Japones", "label": "Configuración Google Home", "defaultPrice": 0 },
  { "id": "maint_144", "system": "Panel Japones", "label": "Reprogramación", "defaultPrice": 0 },
  { "id": "maint_145", "system": "Panel Japones", "label": "Desinstalación", "defaultPrice": 0 },
  { "id": "maint_146", "system": "Panel Japones", "label": "Reinstalación", "defaultPrice": 0 },
  { "id": "maint_147", "system": "Panel Japones", "label": "Traslado de sistema", "defaultPrice": 0 },
  { "id": "maint_148", "system": "Panel Japones", "label": "Servicio preventivo", "defaultPrice": 0 },
  { "id": "maint_149", "system": "Panel Japones", "label": "Servicio correctivo", "defaultPrice": 0 },
  { "id": "maint_150", "system": "Panel Japones", "label": "Cambio completo del sistema", "defaultPrice": 0 },

  { "id": "maint_151", "system": "Vertical", "label": "Visita técnica", "defaultPrice": 0 },
  { "id": "maint_152", "system": "Vertical", "label": "Diagnóstico técnico", "defaultPrice": 0 },
  { "id": "maint_153", "system": "Vertical", "label": "Diagnóstico de garantía", "defaultPrice": 0 },
  { "id": "maint_154", "system": "Vertical", "label": "Lavado de lamas", "defaultPrice": 0 },
  { "id": "maint_155", "system": "Vertical", "label": "Ajuste de lamas", "defaultPrice": 0 },
  { "id": "maint_156", "system": "Vertical", "label": "Ajuste de giro", "defaultPrice": 0 },
  { "id": "maint_157", "system": "Vertical", "label": "Ajuste de apertura", "defaultPrice": 0 },
  { "id": "maint_158", "system": "Vertical", "label": "Ajuste de riel", "defaultPrice": 0 },
  { "id": "maint_159", "system": "Vertical", "label": "Cambio de lama", "defaultPrice": 0 },
  { "id": "maint_160", "system": "Vertical", "label": "Cambio de pesa inferior", "defaultPrice": 0 },
  { "id": "maint_161", "system": "Vertical", "label": "Cambio de cadenilla inferior", "defaultPrice": 0 },
  { "id": "maint_162", "system": "Vertical", "label": "Cambio de carro", "defaultPrice": 0 },
  { "id": "maint_163", "system": "Vertical", "label": "Cambio de bastón", "defaultPrice": 0 },
  { "id": "maint_164", "system": "Vertical", "label": "Cambio de cordón", "defaultPrice": 0 },
  { "id": "maint_165", "system": "Vertical", "label": "Cambio de mando", "defaultPrice": 0 },
  { "id": "maint_166", "system": "Vertical", "label": "Cambio de riel", "defaultPrice": 0 },
  { "id": "maint_167", "system": "Vertical", "label": "Cambio de tela", "defaultPrice": 0 },
  { "id": "maint_168", "system": "Vertical", "label": "Modernización de riel", "defaultPrice": 0 },
  { "id": "maint_169", "system": "Vertical", "label": "Desinstalación", "defaultPrice": 0 },
  { "id": "maint_170", "system": "Vertical", "label": "Reinstalación", "defaultPrice": 0 },
  { "id": "maint_171", "system": "Vertical", "label": "Traslado de sistema", "defaultPrice": 0 },
  { "id": "maint_172", "system": "Vertical", "label": "Servicio preventivo", "defaultPrice": 0 },
  { "id": "maint_173", "system": "Vertical", "label": "Servicio correctivo", "defaultPrice": 0 },
  { "id": "maint_174", "system": "Vertical", "label": "Cambio completo del sistema", "defaultPrice": 0 },

  { "id": "maint_175", "system": "Horizontal Aluminio", "label": "Visita técnica", "defaultPrice": 0 },
  { "id": "maint_176", "system": "Horizontal Aluminio", "label": "Diagnóstico técnico", "defaultPrice": 0 },
  { "id": "maint_177", "system": "Horizontal Aluminio", "label": "Diagnóstico de garantía", "defaultPrice": 0 },
  { "id": "maint_178", "system": "Horizontal Aluminio", "label": "Lavado general", "defaultPrice": 0 },
  { "id": "maint_179", "system": "Horizontal Aluminio", "label": "Ajuste de escalerillas", "defaultPrice": 0 },
  { "id": "maint_180", "system": "Horizontal Aluminio", "label": "Ajuste de cordones", "defaultPrice": 0 },
  { "id": "maint_181", "system": "Horizontal Aluminio", "label": "Cambio de lámina", "defaultPrice": 0 },
  { "id": "maint_182", "system": "Horizontal Aluminio", "label": "Cambio de escalerilla", "defaultPrice": 0 },
  { "id": "maint_183", "system": "Horizontal Aluminio", "label": "Cambio de cordón", "defaultPrice": 0 },
  { "id": "maint_184", "system": "Horizontal Aluminio", "label": "Cambio de bastón", "defaultPrice": 0 },
  { "id": "maint_185", "system": "Horizontal Aluminio", "label": "Cambio de freno", "defaultPrice": 0 },
  { "id": "maint_186", "system": "Horizontal Aluminio", "label": "Cambio de cabezal", "defaultPrice": 0 },
  { "id": "maint_187", "system": "Horizontal Aluminio", "label": "Cambio de mecanismo", "defaultPrice": 0 },
  { "id": "maint_188", "system": "Horizontal Aluminio", "label": "Desinstalación", "defaultPrice": 0 },
  { "id": "maint_189", "system": "Horizontal Aluminio", "label": "Reinstalación", "defaultPrice": 0 },
  { "id": "maint_190", "system": "Horizontal Aluminio", "label": "Traslado de sistema", "defaultPrice": 0 },
  { "id": "maint_191", "system": "Horizontal Aluminio", "label": "Servicio preventivo", "defaultPrice": 0 },
  { "id": "maint_192", "system": "Horizontal Aluminio", "label": "Servicio correctivo", "defaultPrice": 0 },
  { "id": "maint_193", "system": "Horizontal Aluminio", "label": "Cambio completo del sistema", "defaultPrice": 0 },

  { "id": "maint_194", "system": "Madera", "label": "Visita técnica", "defaultPrice": 0 },
  { "id": "maint_195", "system": "Madera", "label": "Diagnóstico técnico", "defaultPrice": 0 },
  { "id": "maint_196", "system": "Madera", "label": "Diagnóstico de garantía", "defaultPrice": 0 },
  { "id": "maint_197", "system": "Madera", "label": "Limpieza especializada", "defaultPrice": 0 },
  { "id": "maint_198", "system": "Madera", "label": "Restauración de acabado", "defaultPrice": 0 },
  { "id": "maint_199", "system": "Madera", "label": "Ajuste de escalerillas", "defaultPrice": 0 },
  { "id": "maint_200", "system": "Madera", "label": "Ajuste de cordones", "defaultPrice": 0 },
  { "id": "maint_201", "system": "Madera", "label": "Cambio de lama", "defaultPrice": 0 },
  { "id": "maint_202", "system": "Madera", "label": "Cambio de escalerilla", "defaultPrice": 0 },
  { "id": "maint_203", "system": "Madera", "label": "Cambio de cordón", "defaultPrice": 0 },
  { "id": "maint_204", "system": "Madera", "label": "Cambio de bastón", "defaultPrice": 0 },
  { "id": "maint_205", "system": "Madera", "label": "Cambio de cabezal", "defaultPrice": 0 },
  { "id": "maint_206", "system": "Madera", "label": "Cambio de mecanismo", "defaultPrice": 0 },
  { "id": "maint_207", "system": "Madera", "label": "Desinstalación", "defaultPrice": 0 },
  { "id": "maint_208", "system": "Madera", "label": "Reinstalación", "defaultPrice": 0 },
  { "id": "maint_209", "system": "Madera", "label": "Traslado de sistema", "defaultPrice": 0 },
  { "id": "maint_210", "system": "Madera", "label": "Servicio preventivo", "defaultPrice": 0 },
  { "id": "maint_211", "system": "Madera", "label": "Servicio correctivo", "defaultPrice": 0 },
  { "id": "maint_212", "system": "Madera", "label": "Cambio completo del sistema", "defaultPrice": 0 }
];
